### ISSUE TITLE
安装 bigCache 一直失败

### ISSUE THREAD

**Issue by taojy93** [go-programming-tour-book/cache-example#1]
老师请问一下, 为什么我按照书里面的命令安装bigCache 一直404, 不加版本号的话一直下载的是 1.2.1 版本, 加了 -u 参数也是, 加版本号完全下载不了最新的, 2.2.0 也不行, 用的七牛云的国内代理, 难道一定要科学上网才行吗?

**Comment by polaris1119** [comment]
贴下你的 go get 命令

**Comment by taojy93** [comment]
> 贴下你的 go get 命令

go get -u github.com/allegro/bigcache@v2.2.0
或者
go get -u github.com/allegro/bigcache@v2.2.4
都会报错

如果 go get -u github.com/allegro/bigcache
就只会下载 v1.2.1, 我想下载比较新的包

**Comment by taojy93** [comment]
报错信息如下:
```
go get github.com/allegro/bigcache@v2.2.0: github.com/allegro/bigcache@v2.2.0: reading https://goproxy.cn/github.com/allegro/bigcache/@v/v2.2.0.info: 404 Not Found
        server response: not found: github.com/allegro/bigcache@v2.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
国内不是就七牛云这个代理镜像比较好吗?是说明他的包更新同步非常滞后吗?我该怎么做呢?

**Comment by polaris1119** [comment]
go get -u github.com/allegro/bigcache/v2 

这样
